### ISSUE TITLE
[Question] duplicate function exports 

### ISSUE THREAD

**Issue by orrybaram** [kesla/map-upsert#2]
Genuine question, how are you able to export 2 function types and 1 function all with the same name?

https://github.com/kesla/map-upsert/blob/3a33740aaea36fb017a1a1712134f8668cc14537/lib/index.ts#L18

**Comment by kesla** [comment]
Hey Orry,

Thanks for the question!

It's described here: https://www.typescriptlang.org/docs/handbook/functions.html#overloads.

The overloading functionality is pretty cool, in this case I need it to be able to support both Map:s and WeakMap:s - as well as having strict type security for the keys.

It means, for example, that if I try to use upsert with the wrong type of key, this is an error when compiling typescript

```typescript
const map = new WeakMap<any, any>()
upsert(map, 'foo', updateFn, insertFn) // won't compile since you can't use strings with WeakMap:s
```

While this is not

```typescript
const map = new Map<any, any>()
upsert(map, 'foo', updateFn, insertFn)
```

**Comment by orrybaram** [comment]
Ah, thanks for the explanation. Didn't know you could overload functions
like this. This is actually super useful.

**Comment by kesla** [comment]
Yeah, it's great. Took me some time to figure out how to get it correct in here, so happy you dropped by and asked about it!

Adios, my friend
